name: Example

on:
  push:
    branches:
      - master
      - staging
  pull_request:
    branches:
      - master
      - staging

jobs:
  build_and_test:
    name: Build and test1
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Commit assets
        uses: EndBug/add-and-commit@v5
        if: ${{github.ref == 'refs/heads/master' || github.ref == 'refs/heads/staging'}}
        with:
          message: "Commit assets: ${{github.event.head_commit.message}}"

  build_and_test2:
    name: Build and test2
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Commit assets
        uses: EndBug/add-and-commit@v5
        with:
          message: "Commit assets: ${{github.event.head_commit.message}}"

  deploy1:
    name: Deploy1
    runs-on: ubuntu-latest
    needs: build_and_test
    if: contains(github.ref, 'staging') || contains(github.ref, 'master')
    steps:
      - name: Deploy Web Service - Staging
        run: |
          echo "deploy1 with IF, only in master."
          echo ${{ github.ref }}
          echo ${{ github.base_ref }}

  deploy2:
    name: Deploy2
    runs-on: ubuntu-latest
    needs: build_and_test2
    steps:
      - name: Deploy Web Service - Staging
        run: |
          echo "deploy2 without IF."
          echo ${{ github.ref }}
          echo ${{ github.base_ref }}
